#!/usr/bin/env bash
set -euo pipefail

# CONFIGURATION
ENV_NAME="${ENV_NAME:-mol_gtn}"
INPUT_CSV="${INPUT_CSV:-./pretraining.csv}"
SAMPLED_CSV="${SAMPLED_CSV:-./pretraining_1m.csv}"
RAMDISK_CSV="${RAMDISK_CSV:-/dev/shm/pretraining_1m.csv}"
SAMPLE_ROWS="${SAMPLE_ROWS:-1000000}"
SAMPLE_SEED="${SAMPLE_SEED:-42}"
OUTPUT_DIR="${OUTPUT_DIR:-/hy-tmp/result_flash_1m}"
FULL_LMDB_PATH="${FULL_LMDB_PATH:-/hy-tmp/result_flash_1m/pretraining_1m.lmdb}"
MEDIUM_LMDB_PATH="${MEDIUM_LMDB_PATH:-/hy-tmp/result/ddp_medium_50k.lmdb}"
MODEL_PATH="${MODEL_PATH:-/hy-tmp/result_flash_1m/model_final.pth}"
OSS_TARGET_DIR="${OSS_TARGET_DIR:-oss://backup/}"
AUTO_UPLOAD_AND_SHUTDOWN="${AUTO_UPLOAD_AND_SHUTDOWN:-1}"
GPUS="${GPUS:-4}"
BATCH_PER_GPU="${BATCH_PER_GPU:-32}"
MAX_NODES_PER_BATCH="${MAX_NODES_PER_BATCH:-2048}"
GRAD_ACCUM_STEPS="${GRAD_ACCUM_STEPS:-2}"
SCALED_LEARNING_RATE="${SCALED_LEARNING_RATE:-0.0003}"
EPOCHS="${EPOCHS:-10}"
PREPROCESS_WORKER_COUNT="${PREPROCESS_WORKER_COUNT:-96}"
TASK_QUEUE_MAXSIZE="${TASK_QUEUE_MAXSIZE:-192}"
RESULT_QUEUE_MAXSIZE="${RESULT_QUEUE_MAXSIZE:-192}"
WRITER_BATCH_SIZE="${WRITER_BATCH_SIZE:-256}"
CPU_RESERVE_THREADS="${CPU_RESERVE_THREADS:-4}"
RUN_MEDIUM_STRESS_TEST="${RUN_MEDIUM_STRESS_TEST:-1}"
STRESS_STEPS="${STRESS_STEPS:-200}"
LAP_PE_DIM="${LAP_PE_DIM:-8}"
MASK_RATIO="${MASK_RATIO:-0.1}"
NUM_MASKED_VIEWS="${NUM_MASKED_VIEWS:-6}"
DATA_MODE="${DATA_MODE:-auto}"
RESUME_FROM="${RESUME_FROM:-}"
RUN_TIMESTAMP="${RUN_TIMESTAMP:-}"
AUDIT_SAMPLE_COUNT="${AUDIT_SAMPLE_COUNT:-512}"
LOSS_LOG_EVERY_STEPS="${LOSS_LOG_EVERY_STEPS:-10}"
LOSS_FLUSH_EVERY_STEPS="${LOSS_FLUSH_EVERY_STEPS:-100}"
HIDDEN_DIM="${HIDDEN_DIM:-256}"
NUM_LAYERS="${NUM_LAYERS:-6}"
TEMPERATURE="${TEMPERATURE:-0.07}"

cleanup() {
  rm -f "${RAMDISK_CSV}"
}

trap cleanup EXIT

if [[ ! -d /dev/shm ]]; then
  echo "[Moving to RAM Disk] /dev/shm not found; aborting." >&2
  exit 1
fi

source /usr/local/miniconda3/etc/profile.d/conda.sh
conda activate "${ENV_NAME}"

echo "[Sampling] Creating ${SAMPLE_ROWS}-row sample at ${SAMPLED_CSV}"
python sample_pretraining_csv.py \
  --input "${INPUT_CSV}" \
  --output "${SAMPLED_CSV}" \
  --rows "${SAMPLE_ROWS}" \
  --seed "${SAMPLE_SEED}"

echo "[Moving to RAM Disk] Copying ${SAMPLED_CSV} -> ${RAMDISK_CSV}"
cp "${SAMPLED_CSV}" "${RAMDISK_CSV}"
chmod 644 "${RAMDISK_CSV}"
ls -lh "${RAMDISK_CSV}"

echo "[Starting Pipeline] Launching final_fullscale_run.sh on RAM-disk CSV"
CSV_PATH="${RAMDISK_CSV}" \
OUTPUT_DIR="${OUTPUT_DIR}" \
FULL_LMDB_PATH="${FULL_LMDB_PATH}" \
MEDIUM_LMDB_PATH="${MEDIUM_LMDB_PATH}" \
MODEL_PATH="${MODEL_PATH}" \
GPUS="${GPUS}" \
BATCH_PER_GPU="${BATCH_PER_GPU}" \
MAX_NODES_PER_BATCH="${MAX_NODES_PER_BATCH}" \
GRAD_ACCUM_STEPS="${GRAD_ACCUM_STEPS}" \
SCALED_LEARNING_RATE="${SCALED_LEARNING_RATE}" \
EPOCHS="${EPOCHS}" \
PREPROCESS_WORKER_COUNT="${PREPROCESS_WORKER_COUNT}" \
TASK_QUEUE_MAXSIZE="${TASK_QUEUE_MAXSIZE}" \
RESULT_QUEUE_MAXSIZE="${RESULT_QUEUE_MAXSIZE}" \
WRITER_BATCH_SIZE="${WRITER_BATCH_SIZE}" \
CPU_RESERVE_THREADS="${CPU_RESERVE_THREADS}" \
RUN_MEDIUM_STRESS_TEST="${RUN_MEDIUM_STRESS_TEST}" \
STRESS_STEPS="${STRESS_STEPS}" \
LAP_PE_DIM="${LAP_PE_DIM}" \
MASK_RATIO="${MASK_RATIO}" \
NUM_MASKED_VIEWS="${NUM_MASKED_VIEWS}" \
DATA_MODE="${DATA_MODE}" \
RESUME_FROM="${RESUME_FROM}" \
RUN_TIMESTAMP="${RUN_TIMESTAMP}" \
AUDIT_SAMPLE_COUNT="${AUDIT_SAMPLE_COUNT}" \
LOSS_LOG_EVERY_STEPS="${LOSS_LOG_EVERY_STEPS}" \
LOSS_FLUSH_EVERY_STEPS="${LOSS_FLUSH_EVERY_STEPS}" \
HIDDEN_DIM="${HIDDEN_DIM}" \
NUM_LAYERS="${NUM_LAYERS}" \
TEMPERATURE="${TEMPERATURE}" \
AUTO_UPLOAD_AND_SHUTDOWN="${AUTO_UPLOAD_AND_SHUTDOWN}" \
OSS_TARGET_DIR="${OSS_TARGET_DIR}" \
./final_fullscale_run.sh
